apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: httpserver
  namespace: istio-system
spec:
  dnsNames:
    - cnc12.gocloudnative.work
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: letsencrypt-ca
  secretName: httpserver
  usages:
    - digital signature
    - key encipherment
